# Generated by Django 5.1 on 2024-10-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nezarat', '0005_remove_user_group_user_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='position',
            new_name='TITLe',
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, choices=[('O', 'Operator'), ('S', 'SarShift'), ('C', 'Captain')], max_length=1),
        ),
    ]
