# Generated by Django 5.1 on 2024-10-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nezarat', '0007_rename_title_user_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, choices=[('O', 'Operator'), ('S', 'SarShift'), ('C', 'Captain'), ('A', 'Admin')], max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, choices=[('E', 'employee'), ('C', 'Company')], max_length=1),
        ),
    ]
