# Generated by Django 5.1 on 2024-10-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nezarat', '0008_alter_employee_position_alter_user_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, choices=[('E', 'Employee'), ('C', 'Company')], max_length=1),
        ),
    ]
