# Generated by Django 5.1.1 on 2024-10-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nezarat', '0009_alter_user_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('O', 'Operator'), ('S', 'SarShift'), ('C', 'Captain'), ('A', 'Admin')], max_length=1),
        ),
    ]
