# Generated by Django 5.1.1 on 2024-10-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nezarat', '0010_remove_employee_position_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('O', 'Operator'), ('S', 'SarShift'), ('C', 'Captain'), ('A', 'Admin')], max_length=1, null=True),
        ),
    ]
