# Generated by Django 5.1.1 on 2024-10-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nezarat', '0012_alter_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('U', 'Uncertain'), ('O', 'Operator'), ('S', 'SarShift'), ('C', 'Captain')], default='U', max_length=1, null=True),
        ),
    ]
