# Generated by Django 5.1.1 on 2024-10-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nezarat', '0014_alter_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='position',
            field=models.CharField(blank=True, choices=[('U', 'Uncertain'), ('O', 'Operator'), ('S', 'SarShift'), ('C', 'Captain')], default='U', max_length=1),
        ),
    ]
