# Generated by Django 5.1.1 on 2024-10-08 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nezarat', '0015_jobapplication_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_Emploee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, choices=[('U', 'Uncertain'), ('O', 'Operator'), ('S', 'SarShift'), ('C', 'Captain')], default='U', max_length=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nezarat.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nezarat.employee')),
            ],
        ),
    ]
