# Generated by Django 5.1.1 on 2024-10-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nezarat', '0016_my_emploee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='My_Emploee',
            new_name='My_Employee',
        ),
    ]
