# Generated by Django 5.1.1 on 2024-10-09 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nezarat', '0020_part_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='part',
        ),
        migrations.DeleteModel(
            name='Travel',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
