# Generated by Django 5.1.1 on 2024-10-09 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nezarat', '0022_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=100)),
                ('attribute_value', models.CharField(max_length=100)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_attributes', to='Nezarat.part')),
            ],
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
