# Generated by Django 5.1.1 on 2024-10-10 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nezarat', '0023_customattribute_delete_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='kashti_pictures/Kashti/')),
            ],
        ),
        migrations.CreateModel(
            name='ShipPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Kashti',
        ),
        migrations.AddField(
            model_name='part',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shippart',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nezarat.part'),
        ),
        migrations.AddField(
            model_name='shippart',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nezarat.ship'),
        ),
    ]
