# Generated by Django 5.1.1 on 2024-10-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nezarat', '0024_ship_shippart_delete_kashti_part_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='company_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ship',
            name='company_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
