# Generated by Django 5.1.1 on 2024-10-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nezarat', '0025_part_company_code_ship_company_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='company_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ship',
            name='company_code',
            field=models.CharField(max_length=50),
        ),
    ]
