# Generated by Django 5.1.1 on 2024-10-18 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nezarat', '0027_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
    ]
