# Generated by Django 5.1.3 on 2024-11-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nezarat', '0030_message_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='warehouse',
            field=models.CharField(blank=True, choices=[('1', 'warhouse1'), ('2', 'warhouse2'), ('3', 'warhouse3'), ('4', 'warhouse4'), ('5', 'warhouse5')], default='1', max_length=1),
        ),
    ]
