# Generated by Django 5.1.3 on 2024-11-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nezarat', '0031_part_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='position',
            field=models.CharField(blank=True, choices=[('U', 'Uncertain'), ('OA', 'OperatorA'), ('OB', 'OperatorB'), ('OS', 'OperatorS'), ('C', 'Captain')], default='U', max_length=2),
        ),
        migrations.AlterField(
            model_name='my_employee',
            name='position',
            field=models.CharField(blank=True, choices=[('U', 'Uncertain'), ('OA', 'OperatorA'), ('OB', 'OperatorB'), ('OS', 'OperatorS'), ('C', 'Captain')], default='U', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('U', 'Uncertain'), ('OA', 'OperatorA'), ('OB', 'OperatorB'), ('OS', 'OperatorS'), ('C', 'Captain')], default='U', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, choices=[('E', 'Employee'), ('C', 'Company')], max_length=2),
        ),
    ]
