# Generated by Django 5.1.3 on 2024-12-04 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nezarat', '0032_alter_jobapplication_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='registration_code',
            new_name='company_code',
        ),
    ]
