# Generated by Django 5.1.2 on 2025-01-25 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nezarat', '0039_alter_company_user_alter_employee_user_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='company_code',
            field=models.CharField(max_length=50, verbose_name='کد شرکت'),
        ),
        migrations.AlterField(
            model_name='part',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا'),
        ),
        migrations.AlterField(
            model_name='part',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='kashti_pictures/Part/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام قطعه'),
        ),
        migrations.AlterField(
            model_name='part',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='part',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='Nezarat.warehouse', verbose_name='انبار'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='company_code',
            field=models.CharField(max_length=50, verbose_name='کد شرکت'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام انبار'),
        ),
    ]
