# Generated by Django 5.1.2 on 2025-01-27 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nezarat', '0040_alter_part_company_code_alter_part_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_travels', to='Nezarat.warehouse', verbose_name='انبار مبدا')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nezarat.ship', verbose_name='کشتی')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_travels', to='Nezarat.warehouse', verbose_name='انبار مقصد')),
            ],
        ),
        migrations.CreateModel(
            name='TravelPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('action', models.CharField(choices=[('LOAD', 'بارگیری'), ('UNLOAD', 'تخلیه')], max_length=10, verbose_name='عملیات')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nezarat.part', verbose_name='قطعه')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='Nezarat.travel', verbose_name='سفر')),
            ],
        ),
    ]
