# Generated by Django 5.1.2 on 2025-02-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nezarat', '0041_travel_travelpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='customattribute',
            name='company_code',
            field=models.CharField(default='DEFAULT_VALUE', max_length=50, verbose_name='کد شرکت'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='company_code',
            field=models.CharField(default='DEFAULT_COMPANY_CODE', max_length=100),
        ),
        migrations.AddField(
            model_name='travel',
            name='company_code',
            field=models.CharField(default='DEFAULT_COMPANY_CODE', max_length=50, verbose_name='کد شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelpart',
            name='company_code',
            field=models.CharField(default='DEFAULT_COMPANY_CODE', max_length=50, verbose_name='کد شرکت'),
            preserve_default=False,
        ),
    ]
