# Generated by Django 5.1.2 on 2025-02-12 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nezarat', '0042_customattribute_company_code_shipment_company_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customattribute',
            name='company_code',
            field=models.CharField(default='DEFAULT_COMPANY_CODE', max_length=50, verbose_name='کد شرکت'),
        ),
        migrations.CreateModel(
            name='SubWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام زیر انبار')),
                ('company_code', models.CharField(max_length=50, verbose_name='کد شرکت')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_warehouses', to='Nezarat.ship')),
            ],
        ),
    ]
