# Generated by Django 5.1.6 on 2025-03-11 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nezarat', '0043_alter_customattribute_company_code_subwarehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات کالا'),
        ),
        migrations.AddField(
            model_name='part',
            name='subwarehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Nezarat.subwarehouse', verbose_name='زیرانبار'),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateTimeField(verbose_name='تاریخ یادآوری')),
                ('note', models.TextField(blank=True, null=True, verbose_name='توضیحات یادآوری')),
                ('company_code', models.CharField(max_length=50, verbose_name='کد شرکت')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='Nezarat.part')),
            ],
        ),
    ]
