# Generated by Django 5.1.6 on 2025-03-19 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nezarat', '0044_part_description_part_subwarehouse_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='is_worn_out',
            field=models.BooleanField(default=False, verbose_name='فرسوده شده؟'),
        ),
        migrations.AlterField(
            model_name='part',
            name='company_code',
            field=models.CharField(default='UNKNOWN', max_length=50, verbose_name='کد شرکت'),
        ),
        migrations.AlterField(
            model_name='shippart',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship_parts', to='Nezarat.ship'),
        ),
        migrations.AlterField(
            model_name='subwarehouse',
            name='company_code',
            field=models.CharField(default='UNKNOWN', max_length=50, verbose_name='کد شرکت'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='company_code',
            field=models.CharField(default='UNKNOWN', max_length=50, verbose_name='کد شرکت'),
        ),
        migrations.AlterField(
            model_name='travelpart',
            name='company_code',
            field=models.CharField(default='UNKNOWN', max_length=50, verbose_name='کد شرکت'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='company_code',
            field=models.CharField(default='UNKNOWN', max_length=50, verbose_name='کد شرکت'),
        ),
    ]
