# Generated by Django 5.1.6 on 2025-03-25 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nezarat', '0045_part_is_worn_out_alter_part_company_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('part', 'قطعه'), ('ship', 'کشتی'), ('warehouse', 'انبار'), ('subwarehouse', 'زیرانبار'), ('travel', 'سفر')], default='part', max_length=20, verbose_name='نوع یادآوری'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder',
            name='ship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Nezarat.ship'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='subwarehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Nezarat.subwarehouse'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='travel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Nezarat.travel'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Nezarat.warehouse'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Nezarat.part'),
        ),
    ]
