# Generated by Django 5.1.6 on 2025-03-26 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nezarat', '0047_transportitem_transportoperation_delete_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='employee',
            name='assigned_ship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Nezarat.ship'),
        ),
        migrations.AddField(
            model_name='employee',
            name='assigned_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Nezarat.warehouse'),
        ),
        migrations.AddField(
            model_name='part',
            name='is_consumable',
            field=models.BooleanField(default=False, verbose_name='قطعه مصرفی است؟'),
        ),
        migrations.AddField(
            model_name='part',
            name='storage_column',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='storage_row',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='storage_shelf',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='usage_limit_km',
            field=models.FloatField(blank=True, null=True, verbose_name='حداکثر مسافت قابل تحمل (کیلومتر)'),
        ),
        migrations.AddField(
            model_name='part',
            name='worn_out_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transportitem',
            name='used_in_trip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='company_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='employee_pics/'),
        ),
        migrations.AlterField(
            model_name='part',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا'),
        ),
        migrations.AlterField(
            model_name='transportitem',
            name='from_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nezarat.warehouse'),
        ),
        migrations.AlterField(
            model_name='transportitem',
            name='is_consumable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transportitem',
            name='is_worn_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transportitem',
            name='to_subwarehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Nezarat.subwarehouse'),
        ),
        migrations.AlterField(
            model_name='transportitem',
            name='usage_percent',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('CONFIRMED', 'تأیید شده'), ('REJECTED', 'رد شده')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to='Nezarat.part')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=100)),
                ('attribute_value', models.CharField(max_length=255)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_attributes', to='Nezarat.part')),
            ],
        ),
        migrations.CreateModel(
            name='ShipAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=100, verbose_name='نام ویژگی')),
                ('attribute_value', models.CharField(max_length=255, verbose_name='مقدار ویژگی')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='Nezarat.ship')),
            ],
        ),
        migrations.CreateModel(
            name='ShipSubWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام زیرانبار کشتی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد مکان (مثلاً C2-L1)')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship_sub_warehouses', to='Nezarat.ship')),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='ship_subwarehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Nezarat.shipsubwarehouse', verbose_name='زیرانبار کشتی'),
        ),
        migrations.AddField(
            model_name='transportitem',
            name='ship_subwarehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Nezarat.shipsubwarehouse'),
        ),
        migrations.AddField(
            model_name='transportoperation',
            name='ship_subwarehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Nezarat.shipsubwarehouse', verbose_name='زیرانبار کشتی'),
        ),
        migrations.CreateModel(
            name='WarehouseSubStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام زیرانبار')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد مکان (مثلاً R2-S3-A)')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_storages', to='Nezarat.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='warehouse_sub_storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Nezarat.warehousesubstorage', verbose_name='زیرانبار انبار (در صورت وجود)'),
        ),
    ]
