# Generated by Django 5.1.6 on 2025-03-27 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nezarat', '0049_shippart_location_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportitem',
            name='to_subwarehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Nezarat.warehousesubstorage'),
        ),
        migrations.RemoveField(
            model_name='part',
            name='subwarehouse',
        ),
        migrations.AlterField(
            model_name='reminder',
            name='subwarehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Nezarat.warehousesubstorage'),
        ),
        migrations.RemoveField(
            model_name='part',
            name='worn_out_reason',
        ),
        migrations.AlterField(
            model_name='part',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا'),
        ),
        migrations.AlterField(
            model_name='part',
            name='warehouse_sub_storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Nezarat.warehousesubstorage', verbose_name='زیرانبار انبار'),
        ),
        migrations.DeleteModel(
            name='SubWarehouse',
        ),
    ]
