# Generated by Django 5.1.6 on 2025-03-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nezarat', '0050_alter_transportitem_to_subwarehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='part',
            name='worn_out_reason',
            field=models.TextField(blank=True, null=True, verbose_name='دلیل فرسودگی'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('part', 'قطعه'), ('ship', 'کشتی'), ('Shipsubwarehouse', 'انبار سوار بر کشتی'), ('warehouse', 'انبار'), ('WarehouseSubStorage', 'زیرانبار')], max_length=20, verbose_name='نوع یادآوری'),
        ),

    ]
