# Generated by Django 5.1.6 on 2025-03-28 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nezarat', '0051_jobapplication_is_accepted_message_is_read_and_more'),
    ]


