# Generated by Django 5.1.6 on 2025-03-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nezarat', '0052_remove_jobapplication_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='warehouse_pics/', verbose_name='عکس انبار'),
        ),
    ]
